### ISSUE TITLE
ayarlar tuşları çalışmıyor.

### ISSUE THREAD

**Issue by erenertugrul** [Visual917/PS2RPC#1]
ayarlar tusuna tıklıyorum tıklıyorum calismiyor.
gui sesine tıklayınca ses geliyor o kadar. muhtemelen gorsel degismiyor.

![Screen Shot 2020-03-18 at 17 51 43](https://user-images.githubusercontent.com/27224622/76974783-aed25780-6942-11ea-87f0-425c7b5bb64e.png)

**Comment by Visual917** [comment]
Bir göz atıyorum.

**Comment by Visual917** [comment]
1.0b güncellemesi ile sorun çözüldü.

Problem was fixed with the 1.0b update.
